# Generated by Django 2.2.7 on 2019-12-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('published_at', models.DateTimeField()),
                ('phrase', models.TextField()),
                ('author_id', models.BigIntegerField()),
                ('author_name', models.TextField()),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='TweetQueryPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_phrase', models.TextField()),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_phrases', to='collector.Tweet')),
            ],
        ),
        migrations.CreateModel(
            name='TweetHashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.TextField()),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='collector.Tweet')),
            ],
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['published_at'], name='collector_t_publish_a5e979_idx'),
        ),
    ]
